### ISSUE TITLE
Could not find a version that satisfies the requirement anki==2.1.51 (from ki) 

### ISSUE THREAD

**Issue by kevinpolisano** [langfield/ki#114] opened 2023-01-08 14:09 UTC
`pip install git+https://github.com/langfield/ki.git@main`

gives me this error:

```bash
ERROR: Could not find a version that satisfies the requirement anki==2.1.51 (from ki) (from versions: 2.1.24+359b9f5c, 2.1.25, 2.1.26, 2.1.28, 2.1.29, 2.1.30, 2.1.31, 2.1.32, 2.1.33, 2.1.34, 2.1.35)
ERROR: No matching distribution found for anki==2.1.51
```

**Comment by langfield** [comment] 2023-01-08 16:12
Hi! This happens when you're running a Python version that is too old (probably 3.7). Unfortunately, the `anki` maintainers have a taste for breaking backwards compatibility, and the newest versions of the package only work with `3.9+`.

If you need to install multiple python versions side-by-side, I recommend using [`miniconda`](https://docs.conda.io/en/latest/miniconda.html).

**Comment by langfield** [comment] 2023-01-08 16:28
One thing we could do to make this clearer is to check the version in the install command. Perhaps something like this:
```console
(ki-python37) user@computer:~$ python3 --version; python3 --version | grep -q 3.9 && pip install git+https://github.com/langfield/ki.git@main || echo 'Python 3.9+ required'
Python 3.7.13
Python 3.9+ required
```

**Comment by kevinpolisano** [comment] 2023-01-08 16:31
Thanks for the reply.

Indeed I was using Python 3.7.6. I have installed Python 3.11.1 and set PATH such that I got:

```bash
python3 --version
Python 3.11.1
```

```bash
python --version
Python 3.7.6
```

And I still obtain the same error.

Also the output of your install command suggestion gives:

```bash
python3 --version; python3 --version | grep -q 3.9 && pip install git+https://github.com/langfield/ki.git@main || echo 'Python 3.9+ required'
Python 3.7.13
Python 3.11.1
Python 3.9+ required
Python: can't open file '3.7.13': [Errno 2] No such file or directory
```

**Comment by langfield** [comment] 2023-01-08 16:34
Haha, sorry, I was too slow on editing it. Looks like I needed some ORs in there to support higher versions.

Can you check which `pip` version you've got?

**Comment by kevinpolisano** [comment] 2023-01-08 16:38
Yes sure. (I've installed the newest version of Python from the .dmg file downloaded on the official website)

```bash
pip --version
pip 22.3.1 from /Users/polisank/opt/anaconda3/lib/python3.7/site-packages/pip (python 3.7)
```

```bash
pip3 --version
pip 22.3.1 from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip (python 3.11)
```

**Comment by langfield** [comment] 2023-01-08 16:42
Great! So it looks like your `pip` is resolving to `python 3.7` and your `pip3` is resolving to `python 3.11`. This makes sense in light of the error message you posted above.

Try it with this:
```bash
python3 --version; python3 --version | grep -q '3.9\|3.10\|3.11\|3.12' \
  && python3 -m pip install git+https://github.com/langfield/ki.git@main \
  || echo 'Python 3.9+ required'
  ```

**Comment by kevinpolisano** [comment] 2023-01-08 17:09
Thank you it works now!

I have a last quick question. Do you know why some of my cards disappeared on the "Handicap" desk (it seems to contains only one card) but are all still visibles in the browser or the ki clone collection directory?

<img width="581" alt="Capture d’écran 2023-01-08 à 18 02 19" src="https://user-images.githubusercontent.com/25388926/211209407-fa4ac483-81c0-4f7c-bfce-23f5416a870d.png">
<img width="701" alt="Capture d’écran 2023-01-08 à 18 03 35" src="https://user-images.githubusercontent.com/25388926/211209409-b1e340c4-6353-44c8-9e9b-1e4525c7432f.png">

**Comment by kevinpolisano** [comment] 2023-01-08 17:14
By the way, the `ki pull` raises this error:

```bash
polisank  ~/Personnel/PKM/anki-flashcards/collection   main last-successful-ki-push ●                                                    1 ↵  18:11:05
╰─ ki pull
Cloning into '/private/var/folders/qt/n284tq590sbgkbfhdjgffm900000gn/T/tmptaucukxo/ki-remote/6e4580015854085cff16aea212228334'...
Notes: 100%|██████████████████████████████████| 11/11 [00:00<00:00, 1797.12it/s]
Media: 100%|██████████████████████████████████| 11/11 [00:00<00:00, 5670.07it/s]
Fields: 100%|█████████████████████████████████| 11/11 [00:00<00:00, 6823.03it/s]
Decks: 100%|██████████████████████████████████████| 1/1 [00:00<00:00, 91.66it/s]
Updating fd1f16d..d8b9547

From /private/var/folders/qt/n284tq590sbgkbfhdjgffm900000gn/T/tmpw_a7ce84/ki-local-6e4580015854085cff16aea212228334/
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> anki/main
error: Your local changes to the following files would be overwritten by merge:
	.ki/hashes
Please commit your changes or stash them before you merge.
Aborting
```

**Comment by langfield** [comment] 2023-01-08 17:20
@kevinpolisano Fantastic! So to address the disappearing cards, what are you looking at to determine that the deck only contains one card? To my knowledge, the browser is the only way to get a total card count for a deck (it will say something like `1 of 1448 cards selected` at the top).

As for the error you're getting, this can only be a bug, and I would be happy to fix it for you! I will need some way of reproducing the error message. If you are comfortable sharing your collection binary and the sequence of operations you executed, that would be extremely helpful. If you have sensitive data you wouldn't like to share, a minimum working example on a fake collection would be the next best thing. If you don't have the time to do either of those, just a high-level description of the commands you ran would also work.

**Comment by kevinpolisano** [comment] 2023-01-08 17:33
OK sorry for the cards there are not visibles simply because the "due date" is in a couple of day I guess. I thought I could see the cards on Ankiweb but I cannot, when I click on the "Handicap" desk I get this:

<img width="1121" alt="Capture d’écran 2023-01-08 à 18 31 02" src="https://user-images.githubusercontent.com/25388926/211210330-10ee1560-4e4a-45eb-8930-c9092e93aa71.png">
<img width="948" alt="Capture d’écran 2023-01-08 à 18 31 09" src="https://user-images.githubusercontent.com/25388926/211210332-24d3f184-9026-47fe-a2a0-2601a041318d.png">

What is the collection binary you need?

**Comment by langfield** [comment] 2023-01-08 17:43
Sorry, I should have been more clear! The collection binary is your `collection.anki2` file, preferably the original one, before you started using `ki`. That way, I can do the same ops you did and reproduce the state of your collection when you got the error. There should be several backups in your `.ki/backups` directory, and also in the normal Anki backups directory.

**Comment by kevinpolisano** [comment] 2023-01-08 17:51
OK these are the different backups.

Thanks!

[Archive.zip](https://github.com/langfield/ki/files/10369095/Archive.zip)

**Comment by langfield** [comment] 2023-01-08 17:53
Great, and can you tell me what commands you ran to get that error?

If you cannot remember exactly, this would be basically anything in your `.bash_history` or `.zsh_history` that starts with `ki`.

**Comment by kevinpolisano** [comment] 2023-01-08 17:58
<img width="709" alt="Capture d’écran 2023-01-08 à 18 58 00" src="https://user-images.githubusercontent.com/25388926/211211449-74f35e6e-e7da-4ad6-81cf-6ea594835d50.png">

**Comment by kevinpolisano** [comment] 2023-01-08 18:01
I don't know why but now it works :)

```bash
ki pull
Cloning into '/private/var/folders/qt/n284tq590sbgkbfhdjgffm900000gn/T/tmpwrtls0aw/ki-remote/adcf454bcceb4162d0ca2583d0e05017'...
Notes: 100%|██████████████████████████████████| 11/11 [00:00<00:00, 1301.77it/s]
Media: 100%|█████████████████████████████████| 11/11 [00:00<00:00, 10426.52it/s]
Fields: 100%|█████████████████████████████████| 11/11 [00:00<00:00, 6064.32it/s]
Decks: 100%|█████████████████████████████████████| 1/1 [00:00<00:00, 108.06it/s]
Auto-merging .ki/hashes
CONFLICT (content): Merge conflict in .ki/hashes
Automatic merge failed; fix conflicts and then commit the result.

From /private/var/folders/qt/n284tq590sbgkbfhdjgffm900000gn/T/tmp7oqetnfd/ki-local-adcf454bcceb4162d0ca2583d0e05017/
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> anki/main
```

**Comment by kevinpolisano** [comment] 2023-01-08 18:03
A new git pull gives this:

```bash
ki pull
Cloning into '/private/var/folders/qt/n284tq590sbgkbfhdjgffm900000gn/T/tmpwrtls0aw/ki-remote/adcf454bcceb4162d0ca2583d0e05017'...
Notes: 100%|██████████████████████████████████| 11/11 [00:00<00:00, 1301.77it/s]
Media: 100%|█████████████████████████████████| 11/11 [00:00<00:00, 10426.52it/s]
Fields: 100%|█████████████████████████████████| 11/11 [00:00<00:00, 6064.32it/s]
Decks: 100%|█████████████████████████████████████| 1/1 [00:00<00:00, 108.06it/s]
Auto-merging .ki/hashes
CONFLICT (content): Merge conflict in .ki/hashes
Automatic merge failed; fix conflicts and then commit the result.

From /private/var/folders/qt/n284tq590sbgkbfhdjgffm900000gn/T/tmp7oqetnfd/ki-local-adcf454bcceb4162d0ca2583d0e05017/
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> anki/main
```

**Comment by langfield** [comment] 2023-01-08 18:15
Okay, so I see you have done the following:
1. Clone collection
2. Edit a single note
3. Push changes
4. Pull changes

Did you do anything from inside Anki in between steps 3 and 4?

**Comment by kevinpolisano** [comment] 2023-01-08 18:18
Indeed, no nothing else.

**Comment by langfield** [comment] 2023-01-08 18:28
@kevinpolisano Thanks, I believe I've found the source of the bug. It may take me a little while to implement and test the fix.

**Comment by kevinpolisano** [comment] 2023-01-08 18:29
Great! 👍

**Comment by langfield** [comment] 2023-01-08 18:57
Okay, I was unable to reproduce the issue exactly. When I `ki pull` after Step 3, I get this:
```console
(anki) user@computer:~/polisano$ ki pull
ki pull: up to date.
```

However, I think the bug has something to do with `push` leaving the working tree dirty, and in particular, not committing the hashes file. I have fixed this and will push it soon.

If you could try again once the candidate fix is pushed and see if you're still getting the same error, I can try and narrow it down.

**Comment by langfield** [comment] 2023-01-08 19:14
All right, a candidate fix is pushed. I suspect this may not entirely ameliorate the issue. But why don't you try it and we can see what happens and I'll work from there.

**Comment by kevinpolisano** [comment] 2023-01-08 20:08
I have also obtained `ki pull: up to date` 8 seconds later 😄 

<img width="901" alt="Capture d’écran 2023-01-08 à 21 07 16" src="https://user-images.githubusercontent.com/25388926/211216633-494aa658-2cbc-43ce-ae36-f1b2bd7e0a3b.png">

**Comment by langfield** [comment] 2023-01-08 21:45
Wonderful! Feel free to open more issues if you have any further questions, or run into any further bugs.

In particular, if it bothers you in any way at all about the `.ki/hashes` file, that is a bug. This should not be something that end users need worry about.

**Closed by langfield** 2023-01-08 21:45 UTC

**Comment by kevinpolisano** [comment] 2023-01-09 07:31
Thank you very much!
