### ISSUE TITLE
WinError 206: The filename or extension is too long

### ISSUE THREAD

**Issue by pwintz** [langfield/ki#16] opened 2022-08-07 07:37 UTC
When I tried to run `ki clone`, it printed the following error.

```
$ ki clone /c/Users/pwintz/AppData/Roaming/Anki2/Paul/collection.anki2
Cloning.
Found .anki2 file at 'C:\Users\pwintz\AppData\Roaming\Anki2\Paul\collection.anki2'
Computed md5sum: 0d120bb433ba3bf106c0696cbca101d3
Cloning into 'C:\Users\pwintz\flashcards\collection'...
Notes: 100%|##############################| 3594/3594 [00:02<00:00, 1694.55it/s]
HTML:   0%|                                               | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\Scripts\ki-script.py", line 33, in <module>
    sys.exit(load_entry_point('ki==0.0.1a0', 'console_scripts', 'ki')())
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1598, in clone
    _, _ = _clone(col_file, targetdir, msg="Initial commit", silent=False)
  File "<@beartype(ki._clone) at 0x1a00b224040>", line 86, in _clone
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1656, in _clone
    write_repository(col_file, targetdir, leaves, directories.dirs[MEDIA], silent)
  File "<@beartype(ki.write_repository) at 0x1a00b213ee0>", line 106, in write_repository
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1056, in write_repository
    tidy_html_recursively(root, silent)
  File "<@beartype(ki.tidy_html_recursively) at 0x1a00b206a60>", line 49, in tidy_html_recursively
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1400, in tidy_html_recursively
    raise err
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1398, in tidy_html_recursively
    subprocess.run(command, check=False, capture_output=True)
  File "c:\program files\python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\program files\python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\program files\python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 206] The filename or extension is too long
```

**Comment by pwintz** [comment] 2022-08-07 07:44
This may be related to the high amount of nesting I use for my decks. For example, I have a deck named: 
```
General Mathematics::Discrete Math::Set Theory::Relations::Functions
```

**Comment by pwintz** [comment] 2022-08-07 08:53
Ah, I think I figured it out. The sort field for many of my cards are very long, so the names of the corresponding files exceed the Windows file path length limit. Perhaps it would be good to truncate the names to a reasonable length.

**Comment by langfield** [comment] 2022-08-07 10:40
@pwintz Thanks so much for the error report! I am prepared to do *absolutely anything* to accommodate your use case as you are currently my only user!

It's very possible that the paths are too long, and that is what Windows is angry about! I'm not entirely sure. We do truncate the filenames, as you can see below.

https://github.com/langfield/ki/blob/51cc8749ee6a4c5806f60199d18b5ac7f2494fa0/ki/__init__.py#L672-L686

You can also see that I've misspelled `FILENAME`, haha. Gotta fix that. Ignoring the embarrassing typo, you can verify that we aren't writing filenames longer than `~30` characters here:

https://github.com/langfield/ki/blob/51cc8749ee6a4c5806f60199d18b5ac7f2494fa0/ki/__init__.py#L142

But this is still definitely a candidate for the problem, as a particularly long deck tree path could push us over the purported 255 character limit for some Windows systems in some configurations.

Another possibility is discussed in this [StackOverflow answer](https://stackoverflow.com/a/10726266). Basically, the OS may be angry at all the subprocesses we're spinning up indirectly via `html5-tidy`. This may be mitigated by reducing the `BATCH_SIZE` here:

https://github.com/langfield/ki/blob/51cc8749ee6a4c5806f60199d18b5ac7f2494fa0/ki/__init__.py#L1371-L1377

I don't want you to have to worry about any of this, so I'm currently working on getting a Windows CI pipeline up so that I can test this issue, drill down to the crux of the problem, and ship a fix as quickly as possible!

**Comment by langfield** [comment] 2022-08-07 10:45
I don't have a Windows machine on hand, or I'd just try messing with these constants directly to give you a suggestion in as little time as possible. If you absolutely cannot wait a few days (perhaps you're working on a time-sensitive project), I can give you some instructions on how to mess with these yourself if you'd like! Alternatively I can jump on an AWS Windows instance to try and fix this faster.

For now, I'm hard at work trying to get CircleCI to replicate the issue. Will keep you posted! :grimacing:

**Comment by langfield** [comment] 2022-08-07 11:06
In the meantime, I've pushed a branch just for you in case you want to try if a smaller batch size fixes the issue. You can install this version with the following command:
```bash
pip install git+https://github.com/langfield/ki.git@wintz-smaller-tidy-batch-size
```
It reduces the batch size for `tidy` subprocesses from `500` -> `50`.

If you're comfortable sharing your collection file, I can add a test for this issue to the CI tests once I get them working, so that it definitely doesn't regress once it's fixed!

**Comment by pwintz** [comment] 2022-08-08 04:59
Thanks for the fast response! I don't have any particular rush, so it's fine if it takes a few days to fix. I tested `wintz-smaller-tidy-batch-size` and it went further than before, but now it prints a different error:

```
ki clone "C:\Users\pwintz\AppData\Roaming\Anki2\Paul\collection.anki2"
Cloning.
Found .anki2 file at 'C:\Users\pwintz\AppData\Roaming\Anki2\Paul\collection.anki2'
Computed md5sum: 35c03c5398aef28dddb44ebc79ac5fce
Cloning into 'C:\Users\pwintz\flashcards\ki\collection'...
Notes: 100%|##############################| 3594/3594 [00:02<00:00, 1722.72it/s]
HTML: 100%|#####################################| 64/64 [00:04<00:00, 15.50it/s]
Media: 100%|#############################| 3594/3594 [00:00<00:00, 57130.68it/s]
Decks:   0%|                                             | 0/88 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\Scripts\ki-script.py", line 33, in <module>
    sys.exit(load_entry_point('ki==0.0.1a0', 'console_scripts', 'ki')())
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1598, in clone
    _, _ = _clone(col_file, targetdir, msg="Initial commit", silent=False)
  File "<@beartype(ki._clone) at 0x2687b7d1040>", line 86, in _clone
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1656, in _clone
    write_repository(col_file, targetdir, leaves, directories.dirs[MEDIA], silent)
  File "<@beartype(ki.write_repository) at 0x2687b7bfee0>", line 106, in write_repository
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1061, in write_repository
    write_decks(col, targetdir, colnotes, media, tidy_field_files, silent)
  File "<@beartype(ki.write_decks) at 0x2687b7c70d0>", line 122, in write_decks
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1212, in write_decks
    payload: str = get_note_payload(colnote, tidy_field_files)
  File "<@beartype(ki.get_note_payload) at 0x2687b7c7550>", line 48, in get_note_payload
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1314, in get_note_payload
    tidied_field_text: str = tidy_field_files[fid].read_text()
  File "c:\program files\python39\lib\pathlib.py", line 1257, in read_text
    return f.read()
  File "c:\program files\python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 18: character maps to <undefined>
```
My collection is massive and contains some personal information, so I'll try to create a minimum (non)working example that I can share with you. In the meantime, I've cloned `ki` and will try to get it running with a debugger to see if I can give you more info.

**Comment by pwintz** [comment] 2022-08-08 08:55
I edited `write_decks` in 'ki/__init__.py` to have a `try` block inside the `for card_id in descendants` loop so that any cards that fail only result in a warning instead of terminating the process. With this change, cloning my collection finishes with most of the cards working OK. Some of the warnings that are printed are shown below:

```
2022-08-08 01:52:32.881 | WARNING  | ki:get_note_path:694 - Slug for '' is empty. Using '8632c30a6504f89b1e26' as filename
2022-08-08 01:52:32.881 | WARNING  | ki:get_note_path:694 - Slug for '' is empty. Using '05f47c5f4df4c30ad262' as filename
2022-08-08 01:52:32.881 | WARNING  | ki:get_note_path:694 - Slug for '' is empty. Using 'ab909407862c4500feda' as filename
2022-08-08 01:52:32.881 | WARNING  | ki:get_note_path:694 - Slug for '' is empty. Using '27319434ac2a27d6cb7e' as filename
...
2022-08-08 01:52:33.736 | WARNING  | ki:write_decks:1232 - Failed to write card id 1596663699253. Error: 'charmap' codec can't decode byte 0x9d in position 191: character maps to <undefined>
2022-08-08 01:52:33.736 | WARNING  | ki:write_decks:1232 - Failed to write card id 1597032131110. Error: 'charmap' codec can't decode byte 0x9d in position 28: character maps to <undefined>
...
2022-08-08 01:52:34.207 | WARNING  | ki:write_decks:1232 - Failed to write card id 1583047477467. Error: [WinError 1314] A required privilege is not held by the client: 'Math\\Calculus\\fracdd-x-c1csc-x.md' -> 'C:\\Users\\pwintz\\flashcards\\ki\\collection\\Math\\Trigonometry\\fracdd-x-c1csc-x.md'
2022-08-08 01:52:34.239 | WARNING  | ki:write_decks:1232 - Failed to write card id 1622672884313. Error: [WinError 1314] A required privilege is not held by the client: 'Math\\Manifolds\\a-curve-in-a-surface-is-called.md' -> 'C:\\Users\\pwintz\\flashcards\\ki\\collection\\Math\\a-curve-in-a-surface-is-called.md'
2022-08-08 01:52:34.239 | WARNING  | ki:write_decks:1232 - Failed to write card id 1578391670337. Error: [WinError 1314] A required privilege is not held by the client: 'Math\\Topology\\the-c2equivalence-class.md' -> 'C:\\Users\\pwintz\\flashcards\\ki\\collection\\Math\\the-c2equivalence-class.md'
2022-08-08 01:52:34.239 | WARNING  | ki:write_decks:1232 - Failed to write card id 1596523640300. Error: [WinError 1314] A required privilege is not held by the client: 'Math\\Logics and Proofs\\the-c2contrapositive-of.md' -> 'C:\\Users\\pwintz\\flashcards\\ki\\collection\\Math\\the-c2contrapositive-of.md'
```

**Comment by pwintz** [comment] 2022-08-08 09:07
Here's a printout of one of the UnicodeDecodeError.
```
UnicodeDecodeError('charmap', b'<div>\r\n  A function \\(d: M \\times M \xe2\x86\x92 \xe2\x84\x9d\\) is called a\r\n  {{c1::<i>metric</i>}} function if it satisifies:\r\n  <ol>\r\n    <li>{{c2::Positivity}}\r\n    <li>{{c3::Symmetry}}\r\n    <li>{{c4::Triangle Inequality}}\r\n  </ol>\r\n</div>\r\n', 42, 43, 'character maps to <undefined>')
```
The HTML for the corresponding card is as follows:
```
<div>A function <anki-mathjax>d: M \times M → ℝ</anki-mathjax> is called a {{c1::<i>metric</i>}} function if it satisifies:<br><ol><li>{{c2::Positivity}}</li><li>{{c3::Symmetry}}</li><li>{{c4::Triangle Inequality}}</li></ol></div>
```
It seems like the symbols `→` and `ℝ` are the source of the problem. I think it would be reasonable to require users not to use weird Unicode characters (I stopped adding them to cards years ago, but they are still sprinkled throughout), but there should be a nice warning shown when such a character is encountered.

**Comment by langfield** [comment] 2022-08-09 02:56
> Thanks for the fast response! I don't have any particular rush, so it's fine if it takes a few days to fix. I tested `wintz-smaller-tidy-batch-size` and it went further than before, but now it prints a different error:
> 
> ```
> ki clone "C:\Users\pwintz\AppData\Roaming\Anki2\Paul\collection.anki2"
> Cloning.
> Found .anki2 file at 'C:\Users\pwintz\AppData\Roaming\Anki2\Paul\collection.anki2'
> Computed md5sum: 35c03c5398aef28dddb44ebc79ac5fce
> Cloning into 'C:\Users\pwintz\flashcards\ki\collection'...
> Notes: 100%|##############################| 3594/3594 [00:02<00:00, 1722.72it/s]
> HTML: 100%|#####################################| 64/64 [00:04<00:00, 15.50it/s]
> Media: 100%|#############################| 3594/3594 [00:00<00:00, 57130.68it/s]
> Decks:   0%|                                             | 0/88 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "C:\Users\pwintz\AppData\Roaming\Python\Python39\Scripts\ki-script.py", line 33, in <module>
>     sys.exit(load_entry_point('ki==0.0.1a0', 'console_scripts', 'ki')())
>   File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1598, in clone
>     _, _ = _clone(col_file, targetdir, msg="Initial commit", silent=False)
>   File "<@beartype(ki._clone) at 0x2687b7d1040>", line 86, in _clone
>   File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1656, in _clone
>     write_repository(col_file, targetdir, leaves, directories.dirs[MEDIA], silent)
>   File "<@beartype(ki.write_repository) at 0x2687b7bfee0>", line 106, in write_repository
>   File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1061, in write_repository
>     write_decks(col, targetdir, colnotes, media, tidy_field_files, silent)
>   File "<@beartype(ki.write_decks) at 0x2687b7c70d0>", line 122, in write_decks
>   File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1212, in write_decks
>     payload: str = get_note_payload(colnote, tidy_field_files)
>   File "<@beartype(ki.get_note_payload) at 0x2687b7c7550>", line 48, in get_note_payload
>   File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1314, in get_note_payload
>     tidied_field_text: str = tidy_field_files[fid].read_text()
>   File "c:\program files\python39\lib\pathlib.py", line 1257, in read_text
>     return f.read()
>   File "c:\program files\python39\lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 18: character maps to <undefined>
> ```
> 
> My collection is massive and contains some personal information, so I'll try to create a minimum (non)working example that I can share with you. In the meantime, I've cloned `ki` and will try to get it running with a debugger to see if I can give you more info.

That's great! I'm glad you got a chance to try the fix. Too bad there are still problems, but I'm working on it! 

After some playing around, it appears the `UnicodeEncodeError`s and `UnicodeDecodeError`s are caused by `<file>.read()` calls without an explicit encoding. Alas, `pylint` warned me of this and I didn't listen. :roll_eyes: This has been fixed on the [`ki/github-actions`](/langfield/ki/tree/github-actions) branch! But this isn't quite ready to merge yet. I'm actively debugging on that branch, stay tuned!

An example to play around with would be lovely, but I think not entirely necessary now, as I've managed to reproduce all the bugs you've reported via Github Actions.

**Comment by langfield** [comment] 2022-08-09 03:07
> 2022-08-08 01:52:32.881 | WARNING  | ki:get_note_path:694 - Slug for '' is empty. Using '8632c30a6504f89b1e26' as filename
> 2022-08-08 01:52:32.881 | WARNING  | ki:get_note_path:694 - Slug for '' is empty. Using '05f47c5f4df4c30ad262' as filename
> 2022-08-08 01:52:32.881 | WARNING  | ki:get_note_path:694 - Slug for '' is empty. Using 'ab909407862c4500feda' as filename
> 2022-08-08 01:52:32.881 | WARNING  | ki:get_note_path:694 - Slug for '' is empty. Using '27319434ac2a27d6cb7e' as filename

For the empty slug warning, see #27. Low priority for now, really just affects readability of the few affected card filenames.

As for this:

```
Failed to write card id 1583047477467. Error: [WinError 1314] A required privilege is not held by the client: 'Math\\Calculus\\fracdd-x-c1csc-x.md' -> 'C:\\Users\\pwintz\\flashcards\\ki\\collection\\Math\\Trigonometry\\fracdd-x-c1csc-x.md'
```
I'm not sure about this one. Seems somewhat serious. I ought to open a separate issue for this. :thinking:

**Comment by langfield** [comment] 2022-08-10 06:24
@pwintz #31 has been merged into `main`! :tada: This is quite a large changeset, so I wouldn't be surprised if there are some small issues that the tests don't catch on Windows. However, the full test suite (apart from a couple `xfail`s related to #32) passes on a Github actions Windows runner!

**Comment by langfield** [comment] 2022-08-10 06:25
This issue (#16) technically closed by #31, but I'll keep it open until you've confirmed you're able to get core functionality working on your machine.

**Comment by pwintz** [comment] 2022-08-10 09:20
Here's a link to a pared-down version of my collection that exhibits the problems we've discussed above, so that you can include it in the tests, if you'd like: https://drive.google.com/file/d/1COCuyfL7AVPnrGzncWv3_TKRyD4o0eVQ/view?usp=sharing

**Comment by pwintz** [comment] 2022-08-10 09:27
Hmm... 
I'm still seeing the error `[WinError 206] The filename or extension is too` when I try to clone my collection using the code in commit cd0e24e (the current location of the `main` branch). It looks like `BATCH_SIZE` is equal to `499`. When I change it back to `50`, cloning works again.

**Comment by langfield** [comment] 2022-08-10 11:32
> Hmm... I'm still seeing the error `[WinError 206] The filename or extension is too` when I try to clone my collection using the code in commit [cd0e24e](https://github.com/langfield/ki/commit/cd0e24e454cfb7537c320f2e430c15f8148fabb6) (the current location of the `main` branch). It looks like `BATCH_SIZE` is equal to `499`. When I change it back to `50`, cloning works again.

@pwintz Ah, glad I didn't close this yet, then! So here's the problem: I am unable to reproduce the error on 'my' Windows instance, so I cannot tune this parameter. We would like it to be as large as possible while keeping `clone`s working on your machine, with a healthy margin of error in case someone else has the same problem, only more severe.

Here are the options:

1. I open a PR to change it to `50` in `main`, which I can merge once I've determined whether that causes significant performance degradation. I'll merge it either way, I just want to know before I set it and forget it.
2. You can do a sort of manual binary search on your machine to find the largest value where `clone`s will still work, and then we can discuss a margin of error that seems reasonable, and I'll merge that immediately.

**Comment by langfield** [comment] 2022-08-10 19:52
> Here's a link to a pared-down version of my collection that exhibits the problems we've discussed above, so that you can include it in the tests, if you'd like: https://drive.google.com/file/d/1COCuyfL7AVPnrGzncWv3_TKRyD4o0eVQ/view?usp=sharing

Thanks so much for sharing this!

**Comment by pwintz** [comment] 2022-08-11 08:57
On my machine, cloning works with `BATCH_SIZE = 413` but not `BATCH_SIZE = 414`.

**Closed** 2022-08-11 09:46 UTC
Labels: bug
