### ISSUE TITLE
`AnkiAlreadyOpenError` in tests on Windows

### ISSUE THREAD

**Issue by pwintz** [langfield/ki#20] opened 2022-08-08 07:24 UTC
When I try to run many of the tests, e.g., `test_no_op_pull_push_cycle_is_idempotent`, the tests fail due to `AnkiAlreadyOpenError`. Here is the full output:

```
tests\test_integration.py:200 (test_no_op_pull_push_cycle_is_idempotent)
col_file = ExtantFile('C:/Users/pwintz/AppData/Local/Temp/tmp6ts4t6zh/collection.anki2')

    @beartype
    def collection(col_file: ExtantFile) -> Collection:
        try:
>           col = Collection(col_file)

..\ki\maybes.py:266: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <anki.collection.Collection object at 0x000001EAEE437A90>
path = ExtantFile('C:/Users/pwintz/AppData/Local/Temp/tmp6ts4t6zh/collection.anki2')
backend = None, server = False, log = False

    def __init__(
        self,
        path: str,
        backend: RustBackend | None = None,
        server: bool = False,
        log: bool = False,
    ) -> None:
        self._backend = backend or RustBackend(server=server)
        self.db: DBProxy | None = None
        self._should_log = log
        self.server = server
        self.path = os.path.abspath(path)
>       self.reopen()

..\venv\lib\site-packages\anki\collection.py:108: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <anki.collection.Collection object at 0x000001EAEE437A90>
after_full_sync = False

    def reopen(self, after_full_sync: bool = False) -> None:
        if self.db:
            raise Exception("reopen() called with open db")
    
        self._last_checkpoint_at = time.time()
        self._undo: _UndoInfo = None
    
        (media_dir, media_db) = media_paths_from_col_path(self.path)
    
        log_path = ""
        should_log = not self.server and self._should_log
        if should_log:
            log_path = self.path.replace(".anki2", ".log")
    
        # connect
        if not after_full_sync:
>           self._backend.open_collection(
                collection_path=self.path,
                media_folder_path=media_dir,
                media_db_path=media_db,
                log_path=log_path,
            )

..\venv\lib\site-packages\anki\collection.py:294: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <anki._backend.RustBackend object at 0x000001EAEE437250>

    def open_collection(self, *, collection_path: str, media_folder_path: str, media_db_path: str, log_path: str) -> anki.generic_pb2.Empty:
        message = anki.collection_pb2.OpenCollectionRequest(collection_path=collection_path, media_folder_path=media_folder_path, media_db_path=media_db_path, log_path=log_path)
>       raw_bytes = self._run_command(13, 0, message.SerializeToString())

..\venv\lib\site-packages\anki\_backend\generated.py:1668: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <anki._backend.RustBackend object at 0x000001EAEE437250>, service = 13
method = 0
input = b'\n?C:\\Users\\pwintz\\AppData\\Local\\Temp\\tmp6ts4t6zh\\collection.anki2\x12?C:\\Users\\pwintz\\AppData\\Local\\Temp\\tmp6ts4t6zh\\collection.media\x1aCC:\\Users\\pwintz\\AppData\\Local\\Temp\\tmp6ts4t6zh\\collection.media.db2'

    def _run_command(self, service: int, method: int, input: bytes) -> bytes:
        try:
            return self._backend.command(service, method, input)
        except Exception as error:
            error_bytes = bytes(error.args[0])
    
        err = backend_pb2.BackendError()
        err.ParseFromString(error_bytes)
>       raise backend_exception_to_pylib(err)
E       anki.errors.DBError: Anki already open, or media currently syncing.

..\venv\lib\site-packages\anki\_backend\__init__.py:146: DBError

The above exception was the direct cause of the following exception:

    def test_no_op_pull_push_cycle_is_idempotent():
        """Do pull/push not misbehave if you keep doing both?"""
        col_file = get_col_file()
        runner = CliRunner()
        with runner.isolated_filesystem():
    
            # Clone collection in cwd.
            clone(runner, col_file)
            assert os.path.isdir(REPODIR)
    
            os.chdir(REPODIR)
            out = pull(runner)
            assert "Merge made by the" not in out
>           push(runner)

test_integration.py:214: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
<@beartype(tests.test_ki.push) at 0x1eaee897af0>:30: in push
    ???
test_ki.py:330: in push
    res = runner.invoke(ki.ki, ["push"], standalone_mode=False, catch_exceptions=False)
..\venv\lib\site-packages\click\testing.py:408: in invoke
    return_value = cli.main(args=args or (), prog_name=prog_name, **extra)
..\venv\lib\site-packages\click\core.py:1055: in main
    rv = self.invoke(ctx)
..\venv\lib\site-packages\click\core.py:1657: in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
..\venv\lib\site-packages\click\core.py:1404: in invoke
    return ctx.invoke(self.callback, **ctx.params)
..\venv\lib\site-packages\click\core.py:760: in invoke
    return __callback(*args, **kwargs)
<@beartype(ki.push) at 0x1eaee326c10>:10: in push
    ???
..\ki\__init__.py:2023: in push
    remote_repo, _ = _clone(kirepo.col_file, remote_root, msg, silent=True)
<@beartype(ki._clone) at 0x1eaee3265e0>:86: in _clone
    ???
..\ki\__init__.py:1656: in _clone
    write_repository(col_file, targetdir, leaves, directories.dirs[MEDIA], silent)
<@beartype(ki.write_repository) at 0x1eaee3174c0>:106: in write_repository
    ???
..\ki\__init__.py:1033: in write_repository
    col: Collection = M.collection(col_file)
<@beartype(ki.maybes.collection) at 0x1eaee2a09d0>:31: in collection
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

col_file = ExtantFile('C:/Users/pwintz/AppData/Local/Temp/tmp6ts4t6zh/collection.anki2')

    @beartype
    def collection(col_file: ExtantFile) -> Collection:
        try:
            col = Collection(col_file)
        except anki.errors.DBError as err:
>           raise AnkiAlreadyOpenError(str(err)) from err
E           ki.types.AnkiAlreadyOpenError: fatal: Anki already open, or media currently syncing.

..\ki\maybes.py:268: AnkiAlreadyOpenError
```

**Comment by langfield** [comment] 2022-08-08 13:11
I have reproduced this in CI! You can take a look [here](https://github.com/langfield/ki/runs/7723821191?check_suite_focus=true).
```python
=========================== short test summary info ===========================
FAILED tests/test_integration.py::test_version - AssertionError: assert 'ki, ...
FAILED tests/test_integration.py::test_computes_and_stores_md5sum - ki.types....
FAILED tests/test_integration.py::test_no_op_pull_push_cycle_is_idempotent - ...
FAILED tests/test_integration.py::test_output - ki.types.AnkiAlreadyOpenError...
FAILED tests/test_integration.py::test_clone_handles_html - OSError: [WinErro...
FAILED tests/test_integration.py::test_clone_tidying_only_breaks_lines_for_fields_containing_html
FAILED tests/test_integration.py::test_clone_generates_deck_tree_correctly - ...
FAILED tests/test_integration.py::test_pull_writes_changes_correctly - ki.typ...
FAILED tests/test_integration.py::test_pull_unchanged_collection_is_no_op - P...
FAILED tests/test_integration.py::test_pull_avoids_unnecessary_merge_conflicts
FAILED tests/test_integration.py::test_pull_still_works_from_subdirectories
FAILED tests/test_integration.py::test_pull_handles_unexpectedly_changed_checksums
FAILED tests/test_integration.py::test_pull_handles_uncommitted_submodule_commits
FAILED tests/test_integration.py::test_pull_removes_files_deleted_in_remote
FAILED tests/test_integration.py::test_push_writes_changes_correctly - ki.typ...
FAILED tests/test_integration.py::test_push_generates_correct_backup - ki.typ...
FAILED tests/test_integration.py::test_push_doesnt_write_uncommitted_changes
FAILED tests/test_integration.py::test_push_doesnt_fail_after_pull - ki.types...
FAILED tests/test_integration.py::test_no_op_push_is_idempotent - ki.types.An...
FAILED tests/test_integration.py::test_push_deletes_notes - ki.types.AnkiAlre...
FAILED tests/test_integration.py::test_push_still_works_from_subdirectories
FAILED tests/test_integration.py::test_push_deletes_added_notes - ki.types.An...
FAILED tests/test_integration.py::test_push_generates_correct_title_for_notes
FAILED tests/test_integration.py::test_push_displays_errors_from_head_repo_ref
FAILED tests/test_integration.py::test_push_displays_errors_from_notetype_parsing_in_push_deltas_during_model_adding
FAILED tests/test_integration.py::test_push_displays_errors_from_notetype_parsing_in_push_deltas_during_push_flatnote_to_anki
FAILED tests/test_integration.py::test_push_handles_submodules - ki.types.Ank...
FAILED tests/test_integration.py::test_push_writes_media - ki.types.AnkiAlrea...
FAILED tests/test_integration.py::test_push_handles_foreign_models - ki.types...
FAILED tests/test_integration.py::test_push_is_nontrivial_when_pulled_changes_are_reverted
FAILED tests/test_integration.py::test_push_doesnt_unnecessarily_deduplicate_notetypes
FAILED tests/test_integration.py::test_push_is_nontrivial_when_pushed_changes_are_reverted_in_repository
FAILED tests/test_integration.py::test_push_changes_deck_for_moved_notes - OS...
FAILED tests/test_integration.py::test_push_is_trivial_for_committed_submodule_contents
====== 34 failed, 30 passed, 4 xfailed, 87 warnings in 63.47s (0:01:03) =======
Error: Process completed with exit code 1.
```

I was pretty stumped by this for a minute, but it looks like it's caused by the SQLite database lock acquisition. Commenting out calls to `lock()` and `unlock()` makes several more tests pass, and the others fail for different reasons! See the [workflow results](https://github.com/langfield/ki/runs/7726064238?check_suite_focus=true).

**Comment by langfield** [comment] 2022-08-08 13:15
Here is the relevant patch: https://github.com/langfield/ki/commit/d87accfa9f22f73c9558669b4d4cbbbe7dc60a99, and the implementations of `lock()` and `unlock()` are:
https://github.com/langfield/ki/blob/ed63fef9899b3781c8f4d7663ce7197965f38443/ki/__init__.py#L167-L176

https://github.com/langfield/ki/blob/ed63fef9899b3781c8f4d7663ce7197965f38443/ki/__init__.py#L179-L183

**Comment by langfield** [comment] 2022-08-08 13:18
I believe that this is an easy fix. It's possible the database locking doesn't really do anything to prevent intra-program double-opens on Linux/MacOS. Perhaps it only protects against cross-program collisions. But apparently on Windows, it does what you would expect. I think this means that we need to pass the `col: Collection` through to `_clone()` calls within `push()` and `pull()`, instead of instantiating them inside. Not 100% sure on that, but this seems like a fairly trivial thing to debug. I'm optimistic!

**Comment by pwintz** [comment] 2022-08-09 06:02
This looks like it is preventing any `ki pull`s on Windows, so this is blocking me from really testing out `ki`'s ability to sync back and forth with Anki.

**Comment by langfield** [comment] 2022-08-09 07:07
@pwintz Of course! I'll get it merged ASAP, highest priority! If you're really adventurous, you can try installing from the [`ki/github-actions`](/langfield/ki/tree/github-actions) branch, where a temporary fix is already implemented (the `lock()` and `unlock()` calls are just commented-out, for now).

SQLite will still prevent a DB file from being opened in two different places, so this hotfix is _not_ particularly dangerous, IMO.

**Closed** 2022-08-10 06:19 UTC
