### ISSUE TITLE
The ki clone command stuck at **Decks** progress bar for few hours.

### ISSUE THREAD

**Issue by BilderLoong** [langfield/ki#147] opened 2023-07-09 02:20 UTC
I tried a few times, and every time get the same issue.

![image](https://github.com/langfield/ki/assets/45122720/020df6af-0e0a-4744-adb8-72513187e186)

## Context
The Python version is 3.11.3.
I am using Ubuntu 20.04 LTS on **WSL** to run this command.

---

If you need other information, please let me know!

**Comment by langfield** [comment] 2023-07-09 12:42
Hi! Wow your collection must be quite large! Mind running `du -h` and `ls -1 | wc -l` in your media directory?

**Comment by BilderLoong** [comment] 2023-10-16 03:47
I'm sorry for not getting back to you sooner. Here is the output. 
```shell
$du -h; ls -1 | wc -l
3.7G    .
   26853
```
And as you guessed, it is actually quite large. Does this mean I should wait longer for `ki clone` to finish?
Thanks!

**Comment by langfield** [comment] 2023-10-16 13:42
Try doing a `check media` from within your Anki client and deleting unused media (they will be moved to trash, so not  a destructive operation). Do be careful.

Then let me know if those commands show anything substantially different?

**Comment by langfield** [comment] 2023-10-16 13:44
It may also be a **WSL** issue. The filesystem is much slower because it is virtualized.

**Comment by BilderLoong** [comment] 2023-10-17 02:49
> Try doing a `check media` from within your Anki client and deleting unused media (they will be moved to trash, so not a destructive operation). Do be careful.
> 
> Then let me know if those commands show anything substantially different?

I will try it this weekend.

**Comment by langfield** [comment] 2023-10-25 03:00
Duplicate of #39, please continue commenting over there if you try the thing above. 🙂

**Closed by langfield** 2023-10-25 03:00 UTC
